### ISSUE TITLE
Remove "Chunker" functionality

### ISSUE THREAD

**Issue by jwilsjustin** [ammoready/zanders#5]
It's not providing value to us currently (while also causing problems). I wonder if using SAX parsing via nokogiri will help us out: https://github.com/sparklemotion/nokogiri/wiki/Cheat-sheet#sax-parsing

**Comment by viacoffee** [comment]
SAX might be something we can look in to down the road. When I was first switching from the CSV feed to the XML feed I remember messing around with it. But, since the feed isn't properly formatted XML, it was more work than worth at the time.

**Comment by viacoffee** [comment]
https://github.com/ammoready/zanders/compare/f74425c57295...dbf909ff645d
https://github.com/ammoready/zanders/commit/e5dc319f9a3ac059e864fd1a34d3d1fb1e78c702
